const ActionsType = {
  // user
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_USER_DETAIL: 'SET_USER_DETAIL',
  SET_TOKEN: 'SET_TOKEN',
  SET_USER_TYPE: 'SET_USER_TYPE',
  FEATURED_PRODUCTS: 'FEATURED_PRODUCTS',
  FEATURED_ANTIQUES: 'FEATURED_ANTIQUES',
  FEATURED_HANDMADE: 'FEATURED_HANDMADE',
  HANDMADE: 'HANDMADE',
  ANTIQUES: 'ANTIQUES',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  LOADING: 'LOADING',
  ACTIVE_PAGE: 'ACTIVE_PAGE',
  SET_PAGE_NUMBER: 'SET_PAGE_NUMBER',
  SET_BIDDING_CART_DETAILS: 'SET_BIDDING_CART_DETAILS',
  SET_PRODUCT_BIDDING_DETAILS: 'SET_PRODUCT_BIDDING_DETAILS',
  SET_VERIFY_BIDDING: 'SET_VERIFY_BIDDING',
  SET_BIDDING_ID: 'SET_BIDDING_ID',
  SET_BUYER_ID: 'SET_BUYER_ID',
  SET_PRODUCT_ID: 'SET_PRODUCT_ID',
  SET_SELLER_ID: 'SET_SELLER_ID',
  SET_ADDRESS: 'SET_ADDRESS',
  SET_PRICE: 'SET_PRICE',
  SET_CHECKOUT_PRODUCT: 'SET_CHECKOUT_PRODUCT',
  SET_CHECKOUT_BIDDING: 'SET_CHECKOUT_BIDDING',
  SET_INTERMEDIARY_ID: 'SET_INTERMEDIARY_ID',

  // Bargain
  SET_REQUESTS: 'SET_REQUESTS',

  API_ERROR: 'API_ERROR',
  API_SUCCESS: 'API_SUCCESS',
}

export default ActionsType
